name: docker-build

on:
  workflow_run:
    workflows: [web]
    types:
      - completed

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: build/package/app/Dockerfile
          push: true
          tags: mtgto/pediaroute:latest
