name: web
on:
  workflow_run:
    workflows: [test]
    types:
      - completed

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          version: 10
          cache: true
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT
        working-directory: ./web
      - name: pnpm install
        run: pnpm install --frozen-lockfile
        working-directory: ./web
      - name: Lint
        run: pnpm lint
        working-directory: ./web
        env:
          NPM_CONFIG_ESLINT_ARGS: "-f @jamesacarr/github-actions"
