name: web
on:
  push:
    branches: [master]
    paths:
      - 'web/**'
      - '.github/workflows/web.yml'
  pull_request:
    branches: [master]
    paths:
      - 'web/**'
      - '.github/workflows/web.yml'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: web/pnpm-lock.yaml
      - name: pnpm install
        run: pnpm install --frozen-lockfile
        working-directory: ./web
      - name: Lint
        run: pnpm lint
        working-directory: ./web
      - name: Format check
        run: pnpm oxfmt --check src/
        working-directory: ./web
